# Generated by Django 3.0 on 2020-09-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='dateofpurchase',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='pctype',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
    ]
