# Generated by Django 3.0 on 2020-09-14 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200914_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='dateofpurchase',
            new_name='pc_dop',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='pctype',
            new_name='pc_type',
        ),
    ]
